add_newline = false
command_timeout = 1000

format="""
$battery\
$username\
$hostname\
$directory\
$cmake\
$nodejs\
$python\
$vagrant\
$docker_context\
$env_var\
$time\
$status\
$character"""

right_format = """
$git_branch\
$git_status\
$git_metrics\
$git_state\
$git_commit\
"""
[username]
style_user = "green bold"
style_root = "black bold"
format = "[$user]($style)"
disabled = false
show_always = false

[character]
success_symbol = '[ï”](bold bright-blue)[ï”](bold blue)'
error_symbol = '[ï”](bold bright-red)[ï”](bold blue)'
vimcmd_symbol = '[ï“](bold bright-cyan)[ï“](bold blue)'

[directory]
truncation_length = 2
truncation_symbol = ".../"
truncate_to_repo = true
style = 'bold blue'
format = '[ó°‰‹](style) [$path]($style)[$read_only]($read_only_style) '
read_only = 'ó°Œ¾'
home_symbol = 'ó°‹œ'

[battery]
full_symbol = 'ó°¹'
charging_symbol = 'ó°‚„'
discharging_symbol = 'ó°‚ƒ'
empty_symbol = 'ó°‚'
format='[$symbol\($percentage\)]($style)'

[[battery.display]]
threshold = 10
style = 'bold red'

[[battery.display]]
threshold = 20
style = 'bold orange'

[[battery.display]]
threshold = 30
style = 'bold yellow'

[[battery.display]]
threshold = 99
style = 'bold green'

[git_branch]
format = '[$symbol$branch]($style)'
symbol = 'î‚ '

[git_state]
format = '\(:[$state( $progress_current/$progress_total)]($style)\)'

[git_status]
format = '([$all_status$ahead_behind]($style))'
conflicted = '\[[âš”ï¸$count](bright-white bold)\]]'
ahead = '\[[ó±¦²](bright-blue)[$count](bright-white bold)\]'
behind = '\[[ó±¦³]](white)[$count](bright-white bold)\]'
diverged = '\[[ó°ƒ» ](purple)|[ó±¦²](bright-blue)[$ahead_count][ó±¦³](white)[$behind_count](bright-white)\]'
untracked = '\[ï„¨ [$count](bright-white bold)\]'
stashed = '\[[ó°†“ ](yellow) [$count](bright-white bold)\]'
modified = '\[ó°­ (bright-yellow)[$count](bright-white bold)\]'
staged = '\[[ó°„¬ ](bright-green)[$count](bright-white bold)\]'
renamed = '\[[ó°‘•](bright-cyan) [$count](bright-white bold)\]'
deleted = '\[ï’ [$count](bright-white bold)\]'

[git_commit]
commit_hash_length = 8
style = 'bold white'
tag_symbol = 'ó°“¹'

[python]
format  = 'via [${symbol}${pyenv_prefix}\($virtualenv\)]($style)'

[hostname]
ssh_only = true
format = '@[hostname:](blue)'
disabled = false

[status]
disabled = false
symbol = 'ğŸ¤¡'
