add_newline = false
command_timeout = 10000

format="""
$battery\
$username\
$hostname\
$directory\
$cmake\
$nodejs\
$python\
$vagrant\
$docker_context\
$env_var\
$time\
$status\
$character"""

right_format = """
$git_status\
$git_metrics\
$git_state\
$git_commit\
$git_branch\
"""

[character]
success_symbol = '[ï”](bold bright-blue)[ï”](bold blue) '
error_symbol = '[ï”](bold bright-red)[ï”](bold blue) '
vimcmd_symbol = '[ï“](bold bright-cyan)[ï“](bold blue) '
vimcmd_replace_symbol = '[ï“](bold bright-purple)[ï“](bold blue) '
vimcmd_replace_one_symbol = '[ï“](bold bright-green)[ï“](bold blue) '

[directory]
truncation_length = 2
style = 'bold blue'
format = '[ïŠ ](style) [$path]($style)[$read_only]($read_only_style) '
read_only = "ï ½ "
truncation_symbol = ".../"
home_symbol = "ïŸ› "

[battery]
full_symbol = 'ó°¹ '
charging_symbol = 'ó°‚„ '
discharging_symbol = 'ó°‚ƒ '
empty_symbol = 'ó°‚ '
format='[$symbol\($percentage\)]($style) '

[[battery.display]]
threshold = 10
style = 'bold red'

[[battery.display]]
threshold = 20
style = 'bold orange'

[[battery.display]]
threshold = 30
style = 'bold yellow'

[[battery.display]]
threshold = 99
style = 'bold green'

[git_branch]
format = '[$symbol$branch]($style) '
symbol = 'î‚  '

[git_state]
format = '\(:[$state( $progress_current/$progress_total)]($style)\) '

[git_status]
format = '([$all_status$ahead_behind]($style)) '
conflicted = '\[ï²…  [$count](bright-white bold)\] '
ahead = '\[[ó±¦² ](bright-blue)[$count](bright-white bold)\] '
behind = '\[[ó±¦³ ]](white)[$count](bright-white bold)\] '
diverged = '\[[ï—º ](purple)|[ó±¦² ](bright-blue)[$ahead_count][ó±¦³ ](white)[$behind_count](bright-white)\] '
untracked = '\[ï„¨ [$count](bright-white bold)\] '
stashed = '\[[ï£– ](yellow) [$count](bright-white bold)\] '
modified = '\[ğŸ”­ (bright-yellow)[$count](bright-white bold)\] '
staged = '\[[ï± ](bright-green)[$count](bright-white bold)\] '
renamed = '\[[ï ” ](bright-cyan) [$count](bright-white bold)\] '
deleted = '\[ï’ [$count](bright-white bold)\] '

[git_commit]
commit_hash_length = 8
style = 'bold white'
tag_symbol = ' ó°“¹ '

[python]
format  = 'via [${symbol}${pyenv_prefix}\($virtualenv\) ]($style) '

[hostname]
disabled = true

[status]
disabled = false
symbol = 'ğŸ¤¡ '
